#!/bin/bash
# wot - permite generar una wot en una organización
#
# © 2016 fauno <fauno@partidopirata.com.ar>
#
# Copying and distribution of this file, with or without modification,
# are permitted in any medium without royalty provided the copyright
# notice and this notice are preserved.  This file is offered as-is,
# without any warranty.
# 
# http://www.gnu.org/prep/maintain/html_node/License-Notices-for-Other-Files.html
set -e
set -E

domain="${2:-partidopirata.com.ar}"
wot="${domain}.wot.asc"
methods=()

# Chequea que no estamos sourceando
function es_init() {
  test 'xwot' = "x$(basename -- "$0")"
}

# Registra métodos permitidos
function registrar() {
  methods+=($1)
}

# Ayuda
function help() {
  echo 'wot!'
  echo
  echo 'uso:'
  echo 'wot help     - esta ayuda'
  echo "wot exportar - crea un archivo ${wot} para compartir"
  echo "wot importar - importa ${wot} desde este directorio"
  echo 'wot firmar   - firma todas las llaves'
}
registrar help


# TODO: implementar :P
function listar() {
  :
}
registrar listar

# Exporta todas las llaves a un archivo WOT
function exportar() {
  gpg --export --armor "@${domain}" >"${wot}"
}
registrar exportar

# Importa el archivo de WOT
function importar() {
  gpg --import "${wot}"
}
registrar importar

# Trae todas las llaves de la WOT y las firmas
function firmar() {
  gpg --fingerprint "@${domain}" \
	| grep = \
  | cut -d = -f2 \
  | tr -d " " \
  | xargs -rn1 gpg --sign-key
}
registrar firmar

# Ejecuta el comando que llamamos
function init() {
  # Valida que estemos llamando a un metodo que exista :P
  echo "${methods[@]}" | grep -qw "${1}" || exit 1
  ${1}
}

# Solo ejecuta la función de inicio si estamos ejecutando el script,
# no si lo estamos importando desde otro.
es_init && init $1
